"""Stub file for custom_components/reflex_icd11ect/namespace.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal

import reflex as rx
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

from reflex_icd11ect import handler as _handler
from reflex_icd11ect.icd11ect import (
    Icd11ectBrowser,
    Icd11ectCodingTool,
    Icd11ectController,
    browser_window,
    result_window,
    search_input,
)

class Icd11ectNamespace(rx.ComponentNamespace):
    controller = staticmethod(Icd11ectController.create)
    provider = staticmethod(Icd11ectController.create)
    coding_tool = staticmethod(Icd11ectCodingTool.create)
    browser = staticmethod(Icd11ectBrowser.create)
    search_input = staticmethod(search_input)
    result_window = staticmethod(result_window)
    browser_window = staticmethod(browser_window)
    handler = _handler

    @staticmethod
    def __call__(
        *children,
        ino: Var[str] | str | None = None,
        api_server_url: Var[str] | str | None = None,
        api_secured: Var[bool] | bool | None = None,
        source: Literal["foundation", "icf", "mms"]
        | Var[Literal["foundation", "icf", "mms"]]
        | None = None,
        minor_version: Var[str] | str | None = None,
        language: Var[str] | str | None = None,
        source_app: Var[str] | str | None = None,
        height: Var[str] | str | None = None,
        hierarchy_title: Var[str] | str | None = None,
        hierarchy_resizable: Var[bool] | bool | None = None,
        other_postcoordination: Var[bool] | bool | None = None,
        enable_keyboard: Var[bool] | bool | None = None,
        include_diagnostic_criteria: Var[bool] | bool | None = None,
        verbose: Var[bool] | bool | None = None,
        popup_mode: Var[bool] | bool | None = None,
        simplified_mode: Var[bool] | bool | None = None,
        disable_hierarchy: Var[bool] | bool | None = None,
        words_available: Var[bool] | bool | None = None,
        chapters_available: Var[bool] | bool | None = None,
        chapters_filter: Var[str] | str | None = None,
        subtrees_filter: Var[str] | str | None = None,
        flexisearch_available: Var[bool] | bool | None = None,
        search_by_code_or_uri: Var[bool] | bool | None = None,
        medical_coding_mode: Var[bool] | bool | None = None,
        view_selected_uri: Var[bool] | bool | None = None,
        enable_select_button: Literal["all", "allButRoot", "categories", "none"]
        | Var[Literal["all", "allButRoot", "categories", "none"]]
        | None = None,
        browser_search_available: Var[bool] | bool | None = None,
        browser_advanced_search_available: Var[bool] | bool | None = None,
        browser_hierarchy_available: Var[bool] | bool | None = None,
        browser_hierarchy_root_uris: Var[list[str]] | list[str] | None = None,
        browser_uri: Var[str] | str | None = None,
        display_other_foundation_children: Var[bool] | bool | None = None,
        token: Var[str] | str | None = None,
        token_endpoint: Var[str] | str | None = None,
        token_field: Var[str] | str | None = None,
        token_timeout_ms: Var[int] | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_browser_change: EventType[()] | EventType[rx.Var[dict[str, str]]] | None = None,
        on_browser_load: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_search_end: EventType[()] | None = None,
        on_search_start: EventType[()] | None = None,
        on_select: EventType[()] | EventType[rx.Var[dict[str, str]]] | None = None,
        on_token_request: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> Icd11ectCodingTool:
        """Create a Coding Tool.

        Args:
            *children: Extra children rendered after the result window.
            ino: : Instance identifier, rendered as ``data-ctw-ino``. Unique per page.
            api_server_url: : URL of the ICD-API server, e.g. ``https://id.who.int`` for the WHO : cloud or ``http://localhost`` for a local deployment. Required, unless : another instance on the page already provides it.
            api_secured: : Whether the server requires an OAUTH 2.0 bearer token. ``True`` for : the WHO cloud API, ``False`` for a local deployment.
            source: : Classification to use: ``"mms"`` (ICD-11 MMS), ``"icf"`` (ECT >= 1.7) : or ``"foundation"`` (Embedded Browser only). Defaults to ``"mms"``.
            minor_version: : Release to use, e.g. ``"2025-01"``. Defaults to the latest release : the server reports.
            language: : ISO 639-1 language code of the content and of the interface.
            source_app: : Name of your application, reported to WHO's usage analytics.
            height: : Maximum height of the tool, in CSS ``px`` or ``vh`` units.
            hierarchy_title: : Title shown above the hierarchy panel.
            hierarchy_resizable: : Whether the hierarchy panel can be resized with the mouse (ECT >= 1.7).
            other_postcoordination: : Whether the extended postcoordination options are offered (ECT >= 1.7).
            enable_keyboard: : Whether keyboard navigation is enabled. Always off on mobile.
            include_diagnostic_criteria: : Whether diagnostic requirements are included in the content : (ECT >= 1.7).
            verbose: : Whether ECT logs what it does to the browser console.
            popup_mode: : Whether the results are shown as a dropdown below the search box : instead of a block in the page flow.
            simplified_mode: : Whether to show a stripped down output with codes and titles only. : Implies ``disable_hierarchy`` and turns the word list, the chapter : filter and flexisearch off.
            disable_hierarchy: : Whether to hide the ICD-11 hierarchy browser.
            words_available: : Whether the list of related words is shown.
            chapters_available: : Whether the chapter filter is offered to the user (MMS only).
            chapters_filter: : Chapters the search is limited to, semicolon separated, e.g. : ``"01;02;21"``. See :data:`~reflex_icd11ect.constants.MMS_CHAPTERS`.
            subtrees_filter: : Foundation URIs the search is limited to, comma separated.
            flexisearch_available: : Whether the flexible search is used when the strict search finds : nothing.
            search_by_code_or_uri: : Whether typing a code or a URI searches for that entity.
            medical_coding_mode: : Medical coding mode. Undocumented ECT setting, use with care.
            view_selected_uri: : Show the URI of the selection instead of its code. Undocumented ECT : setting, use with care.
            enable_select_button: : Which entities get a select button: ``"none"`` (the ECT default), : ``"categories"``, ``"all"`` or ``"allButRoot"``.
            browser_search_available: : Whether the browser shows its own search box.
            browser_advanced_search_available: : Whether the advanced search is offered (ECT >= 1.7).
            browser_hierarchy_available: : Whether the hierarchy panel is shown (ECT >= 1.7).
            browser_hierarchy_root_uris: : Foundation URIs the hierarchy is restricted to.
            browser_uri: : URI of the entity shown when the browser loads.
            display_other_foundation_children: : Whether children that are not part of the linearization are listed.
            token: : A valid OAUTH 2.0 bearer token (a JWT). Required when : ``api_secured=True`` unless ``token_endpoint`` is set. Keep it in your : state and refresh it from ``on_token_request``.
            token_endpoint: : URL the browser fetches a token from, the pattern WHO documents. The : response must be JSON; see ``token_field``.
            token_field: : Key of the JSON field holding the token in ``token_endpoint``'s : response. Defaults to ``"token"``, falling back to ``"access_token"``.
            token_timeout_ms: : How long to wait, in milliseconds, for the backend to answer : ``on_token_request`` before giving up. Defaults to 15000.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_select: : Fired when the user picks an entity. The handler receives the selected : entity as a mapping; see :class:`~reflex_icd11ect.types.SelectedEntity`.
            on_search_start: : Fired when a search starts.
            on_search_end: : Fired when a search ends, successfully or not.
            on_browser_load: : Fired once, when the Embedded Browser has finished loading.
            on_browser_change: : Fired whenever the Embedded Browser displays another entity. The : handler receives a mapping; see : :class:`~reflex_icd11ect.types.BrowserContent`.
            on_token_request: : Fired when ECT needs a fresh token, i.e. the previous one expired. : Answer it by setting ``token`` to a new value.
            **props: The props of the component. ``placeholder`` and
                ``input_props`` configure the search box, ``window_props``
                the result window.

        Returns:
            The Coding Tool component.

        """
        ...

icd11ect = Icd11ectNamespace()
__all__ = ["Icd11ectNamespace", "icd11ect"]
